name: 'Build and publish Android applications'
on:
  create:
    branches:
      - release/**
  push:
    branches:
    - master
    - dev/**
    paths:
    - TimetableApp/TimetableApp.Droid/**
    - TimetableApp/TimetableApp.Shared/**
    - .github/workflows/**
  pull_request:
    branches:
    - master
    paths:
    - TimetableApp/TimetableApp.Droid/**
    - TimetableApp/TimetableApp.Shared/**
    - .github/workflows/**

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      PACKAGE_NAME: org.azureams.TimetableApp

    name: Build app (Android)
    # Also need to run on Windows Server 2022
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        # Use Visual Studio 2022 or later to avoid some dumb JDK-related errors. 
        vs-version: '[17.0,)'

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore
      run: nuget restore TimetableApp.Uno.sln

    - name: Build
      run: msbuild TimetableApp/TimetableApp.Droid/TimetableApp.Droid.csproj /p:Configuration=Release /p:AndroidBuildApplicationPackage=true

    - name: Publish arm64 APK
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGE_NAME }}-arm64-v8a.apk
        path: TimetableApp/TimetableApp.Droid/bin/Release/${{ env.PACKAGE_NAME }}-arm64-v8a-Signed.apk

    - name: Publish arm APK
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGE_NAME }}-armeabi-v7a.apk
        path: TimetableApp/TimetableApp.Droid/bin/Release/${{ env.PACKAGE_NAME }}-armeabi-v7a-Signed.apk

    - name: Publish x86_64 APK
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGE_NAME }}-x86_64.apk
        path: TimetableApp/TimetableApp.Droid/bin/Release/${{ env.PACKAGE_NAME }}-x86_64-Signed.apk

    - name: Publish x86 APK
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGE_NAME }}-x86.apk
        path: TimetableApp/TimetableApp.Droid/bin/Release/${{ env.PACKAGE_NAME }}-x86-Signed.apk

    - name: Publish multiarch APK
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGE_NAME }}.apk
        path: TimetableApp/TimetableApp.Droid/bin/Release/${{ env.PACKAGE_NAME }}-Signed.apk
