name: 'Build and publish Android applications'
on:
  create:
    branches:
      - release/**
  push:
    branches:
    - master
    - dev/**
    paths:
    - TimetableApp/TimetableApp.Droid/**
    - TimetableApp/TimetableApp.Shared/**
    - .github/workflows/**
  pull_request:
    branches:
    - master
    paths:
    - TimetableApp/TimetableApp.Droid/**
    - TimetableApp/TimetableApp.Shared/**
    - .github/workflows/**

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      PACKAGE_NAME: com.azureams.TimetableApp

    name: Build app (Android)
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.10 --android=10.2

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Restore
      run: nuget restore TimetableApp.Uno.NonWindows.sln

    - name: Build
      run: msbuild TimetableApp/TimetableApp.Droid/TimetableApp.Droid.csproj /t:PackageForAndroid /p:Configuration=Release

    - name: Publish arm64 APK
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGE_NAME }}-arm64-v8a.apk
        path: TimetableApp/TimetableApp.Droid/bin/Release/${{ env.PACKAGE_NAME }}-arm64-v8a-Signed.apk

    - name: Publish arm APK
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGE_NAME }}-armeabi-v7a.apk
        path: TimetableApp/TimetableApp.Droid/bin/Release/${{ env.PACKAGE_NAME }}-armeabi-v7a-Signed.apk

    - name: Publish x86_64 APK
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGE_NAME }}-x86_64.apk
        path: TimetableApp/TimetableApp.Droid/bin/Release/${{ env.PACKAGE_NAME }}-x86_64-Signed.apk

    - name: Publish x86 APK
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGE_NAME }}-x86.apk
        path: TimetableApp/TimetableApp.Droid/bin/Release/${{ env.PACKAGE_NAME }}-x86-Signed.apk

    - name: Publish multiarch APK
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGE_NAME }}.apk
        path: TimetableApp/TimetableApp.Droid/bin/Release/${{ env.PACKAGE_NAME }}-Signed.apk
