name: 'Build and publish Android applications'
on:
  create:
    branches:
      - release/**
  push:
    branches:
    - master
    - dev/**
    paths:
    - TimetableApp/TimetableApp.Droid/**
    - TimetableApp/TimetableApp.Shared/**
    - .github/workflows/**
  pull_request:
    branches:
    - master
    paths:
    - TimetableApp/TimetableApp.Droid/**
    - TimetableApp/TimetableApp.Shared/**
    - .github/workflows/**

jobs:
  build:
    name: Build app (Android)
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.10 --android=10.2

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Restore
      run: nuget restore TimetableApp.Uno.NonWindows.sln

    - name: Build
      run: msbuild TimetableApp/TimetableApp.Droid/TimetableApp.Droid.csproj /t:PackageForAndroid /p:Configuration=Release

    - name: Publish apks
      uses: actions/upload-artifact@v2
      with:
        name: TimetableApp.Droid
        path: TimetableApp/TimetableApp.Droid/bin/Release/*.apk
