name: 'Build and publish Windows applications'
on:
  create:
    branches:
      - release/**
  push:
    branches:
    - master
    - dev/**
    paths:
    - TimetableApp/TimetableApp.Skia.Wpf/**
    - TimetableApp/TimetableApp.Skia.Wpf.Host/**
    - TimetableApp/TimetableApp.Shared/**
    - .github/workflows/**
  pull_request:
    branches:
    - master
    paths:
    - TimetableApp/TimetableApp.Skia.Wpf/**
    - TimetableApp/TimetableApp.Skia.Wpf.Host/**
    - TimetableApp/TimetableApp.Shared/**
    - .github/workflows/**

jobs:
  build:
    name: Build app (WPF)
    runs-on: windows-latest
    steps:
        # Checkout the code
        - uses: actions/checkout@v2

        # Install .NET Core SDK
        - name: Setup .NET
          run: |
            Invoke-WebRequest 'https://dot.net/v1/dotnet-install.ps1' -OutFile 'dotnet-install.ps1'
            ./dotnet-install.ps1 -Channel Current
          shell: pwsh

        - name: Setup MSBuild
          uses: microsoft/setup-msbuild@v1.0.2

        # .NET core, framework dependent binaries.
        - name: Publish .NET Core
          run: dotnet publish TimetableApp/TimetableApp.Skia.Wpf.Host/TimetableApp.Skia.Wpf.Host.csproj -c Release -f netcoreapp3.1

        - name: Publish package .NET Core
          uses: actions/upload-artifact@v2
          with:
            name: TimetableApp.Skia.Wpf.NetCore
            path: TimetableApp/TimetableApp.Skia.Wpf.Host/bin/Release/netcoreapp3.1/publish/**

        - name: Publish standalone .NET Core (x86)
          run: dotnet publish TimetableApp/TimetableApp.Skia.Wpf.Host/TimetableApp.Skia.Wpf.Host.csproj -c Release -f netcoreapp3.1 -p:PublishSingleFile=true -r win-x86 --self-contained false

        - name: Publish standalone package .NET Core (x86)
          uses: actions/upload-artifact@v2
          with:
            name: TimetableApp.Skia.Wpf.NetCore.Standalone.x86
            path: TimetableApp/TimetableApp.Skia.Wpf.Host/bin/Release/netcoreapp3.1/win-x86/publish/TimetableApp.Skia.Wpf.Host.exe

        - name: Publish standalone .NET Core (x64)
          run: dotnet publish TimetableApp/TimetableApp.Skia.Wpf.Host/TimetableApp.Skia.Wpf.Host.csproj -c Release -f netcoreapp3.1 -p:PublishSingleFile=true -r win-x64 --self-contained false

        - name: Publish standalone package .NET Core (x64)
          uses: actions/upload-artifact@v2
          with:
            name: TimetableApp.Skia.Wpf.NetCore.Standalone.x64
            path: TimetableApp/TimetableApp.Skia.Wpf.Host/bin/Release/netcoreapp3.1/win-x64/publish/TimetableApp.Skia.Wpf.Host.exe

        - name: Publish self-contained .NET Core (x86)
          run: dotnet publish TimetableApp/TimetableApp.Skia.Wpf.Host/TimetableApp.Skia.Wpf.Host.csproj -c Release -f netcoreapp3.1 -p:PublishSingleFile=true -r win-x86

        - name: Publish self-contained package .NET Core (x86)
          uses: actions/upload-artifact@v2
          with:
            name: TimetableApp.Skia.Wpf.NetCore.SelfContained.x86
            path: TimetableApp/TimetableApp.Skia.Wpf.Host/bin/Release/netcoreapp3.1/win-x86/publish/TimetableApp.Skia.Wpf.Host.exe

        - name: Publish self-contained .NET Core (x64)
          run: dotnet publish TimetableApp/TimetableApp.Skia.Wpf.Host/TimetableApp.Skia.Wpf.Host.csproj -c Release -f netcoreapp3.1 -p:PublishSingleFile=true -r win-x64

        - name: Publish self-contained package .NET Core (x64)
          uses: actions/upload-artifact@v2
          with:
            name: TimetableApp.Skia.Wpf.NetCore.SelfContained.x64
            path: TimetableApp/TimetableApp.Skia.Wpf.Host/bin/Release/netcoreapp3.1/win-x64/publish/TimetableApp.Skia.Wpf.Host.exe

        # .NET Framework beauty
        - name: Publish portable .NET Framework (x64)
          run: | 
            dotnet publish TimetableApp/TimetableApp.Skia.Wpf.Host/TimetableApp.Skia.Wpf.Host.csproj -c Release -f net472 -r win-x64 --self-contained true
            remove-item TimetableApp\TimetableApp.Skia.Wpf.Host\bin\Release\net472\win-x64\publish\*.pdb
            remove-item TimetableApp\TimetableApp.Skia.Wpf.Host\bin\Release\net472\win-x64\publish\*.dylib
            remove-item -Recurse -Force TimetableApp\TimetableApp.Skia.Wpf.Host\bin\Release\net472\win-x64\publish\x86
            remove-item -Recurse -Force TimetableApp\TimetableApp.Skia.Wpf.Host\bin\Release\net472\win-x64\publish\x64
            remove-item -Recurse -Force TimetableApp\TimetableApp.Skia.Wpf.Host\bin\Release\net472\win-x64\publish\arm64

        - name: Publish portable .NET Framework package (x64)
          uses: actions/upload-artifact@v2
          with:
            name: TimetableApp.Skia.Wpf.x64
            path: TimetableApp/TimetableApp.Skia.Wpf.Host/bin/Release/net472/win-x64/publish/**

        - name: Publish portable .NET Framework (x86)
          run: | 
            dotnet publish TimetableApp/TimetableApp.Skia.Wpf.Host/TimetableApp.Skia.Wpf.Host.csproj -c Release -f net472 -r win-x86 --self-contained true
            remove-item TimetableApp\TimetableApp.Skia.Wpf.Host\bin\Release\net472\win-x86\publish\*.pdb
            remove-item TimetableApp\TimetableApp.Skia.Wpf.Host\bin\Release\net472\win-x86\publish\*.dylib
            remove-item -Recurse -Force TimetableApp\TimetableApp.Skia.Wpf.Host\bin\Release\net472\win-x86\publish\x86
            remove-item -Recurse -Force TimetableApp\TimetableApp.Skia.Wpf.Host\bin\Release\net472\win-x86\publish\x64
            remove-item -Recurse -Force TimetableApp\TimetableApp.Skia.Wpf.Host\bin\Release\net472\win-x86\publish\arm64

        - name: Publish portable .NET Framework package (x86)
          uses: actions/upload-artifact@v2
          with:
            name: TimetableApp.Skia.Wpf.x86
            path: TimetableApp/TimetableApp.Skia.Wpf.Host/bin/Release/net472/win-x86/publish/**