name: 'Build and publish Windows applications'
on:
  create:
    branches:
      - release/**
  push:
    branches:
    - master
    - dev/**
    paths:
    - TimetableApp/TimetableApp.Skia.Wpf/**
    - TimetableApp/TimetableApp.Skia.Wpf.Host/**
    - TimetableApp/TimetableApp.Shared/**
    - .github/workflows/**
  pull_request:
    branches:
    - master
    paths:
    - TimetableApp/TimetableApp.Skia.Wpf/**
    - TimetableApp/TimetableApp.Skia.Wpf.Host/**
    - TimetableApp/TimetableApp.Shared/**
    - .github/workflows/**

jobs:
  build:
    name: Build app (WPF)
    runs-on: windows-latest
    steps:
        # Checkout the code
        - uses: actions/checkout@v2

        # Install .NET Core SDK
        - name: Setup .NET
          run: |
            Invoke-WebRequest 'https://dot.net/v1/dotnet-install.ps1' -OutFile 'dotnet-install.ps1'
            ./dotnet-install.ps1 -Channel Current
          shell: pwsh

        - name: Setup MSBuild
          uses: microsoft/setup-msbuild@v1.0.2

        # .NET core, framework dependent binaries.
        - name: Publish
          run: dotnet publish TimetableApp/TimetableApp.Skia.Wpf.Host/TimetableApp.Skia.Wpf.Host.csproj --configuration Release

        - name: Publish package
          uses: actions/upload-artifact@v2
          with:
            name: TimetableApp.Skia.Wpf
            path: TimetableApp/TimetableApp.Skia.Wpf.Host/bin/Release/netcoreapp3.1/publish/**

        - name: Publish standalone (x86)
          run: dotnet publish TimetableApp/TimetableApp.Skia.Wpf.Host/TimetableApp.Skia.Wpf.Host.csproj --configuration Release -p:PublishSingleFile=true -r win-x86 --self-contained false

        - name: Publish standalone package (x86)
          uses: actions/upload-artifact@v2
          with:
            name: TimetableApp.Skia.Wpf.Standalone.x86
            path: TimetableApp/TimetableApp.Skia.Wpf.Host/bin/Release/netcoreapp3.1/win-x86/publish/TimetableApp.Skia.Wpf.Host.exe

        - name: Publish standalone (x64)
          run: dotnet publish TimetableApp/TimetableApp.Skia.Wpf.Host/TimetableApp.Skia.Wpf.Host.csproj --configuration Release -p:PublishSingleFile=true -r win-x64 --self-contained false

        - name: Publish standalone package (x64)
          uses: actions/upload-artifact@v2
          with:
            name: TimetableApp.Skia.Wpf.Standalone.x64
            path: TimetableApp/TimetableApp.Skia.Wpf.Host/bin/Release/netcoreapp3.1/win-x64/publish/TimetableApp.Skia.Wpf.Host.exe

        - name: Publish self-contained (x86)
          run: dotnet publish TimetableApp/TimetableApp.Skia.Wpf.Host/TimetableApp.Skia.Wpf.Host.csproj --configuration Release -p:PublishSingleFile=true -r win-x86

        - name: Publish self-contained package (x86)
          uses: actions/upload-artifact@v2
          with:
            name: TimetableApp.Skia.Wpf.SelfContained.x86
            path: TimetableApp/TimetableApp.Skia.Wpf.Host/bin/Release/netcoreapp3.1/win-x86/publish/TimetableApp.Skia.Wpf.Host.exe

        - name: Publish self-contained (x64)
          run: dotnet publish TimetableApp/TimetableApp.Skia.Wpf.Host/TimetableApp.Skia.Wpf.Host.csproj --configuration Release -p:PublishSingleFile=true -r win-x64

        - name: Publish self-contained package (x64)
          uses: actions/upload-artifact@v2
          with:
            name: TimetableApp.Skia.Wpf.SelfContained.x64
            path: TimetableApp/TimetableApp.Skia.Wpf.Host/bin/Release/netcoreapp3.1/win-x64/publish/TimetableApp.Skia.Wpf.Host.exe